config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:show, :new, :create, :destroy]

  root to: 'cocktails#index'

  post 'cocktails/:cocktail_id/doses', to: 'doses#create', as: 'cocktail_doses'
  delete '/doses', to: 'doses#destroy', as: 'delete_doses'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(permitted_cocktail_params)

    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def permitted_cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @dose.cocktail = @cocktail
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = Ingredient.find(params[:dose][:ingredient_id])
    @dose = Dose.new
    @dose.cocktail = @cocktail
    @dose.ingredient = @ingredient
    @dose.description = params[:dose][:description]

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:format])
    redirect_to cocktail_path(@dose.cocktail)
    @dose.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
<%= f.input :name  %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.submit 'Add cocktail', class: 'btn btn-danger' %>
<% end %>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/1000x400/?cocktail);">
  <div class="container text-center">
    <h1>Mister Cocktail!</h1>
  </div>
</div>

<div class="container my-3 text-center">
  <div class="cards">
    <% @cocktails.each do |cocktail| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo, crop: :fill %>')">
          <%= link_to cocktail do  %>
            <%= cocktail.name %>
          <% end %>
          <%= link_to "+", cocktail_path(cocktail), method: :delete, data: { confirm: "Are you sure?" }, class: "card-btn card-link-remove" %>
        </div>
    <% end %>
  </div>
  <%= link_to 'Add a new cocktail', new_cocktail_path, class: 'btn btn-danger btn-lg btn-block my-3' %>
</div>

app/views/cocktails/new.html.erb
<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.photo, height: 300, width: 400, crop: :fill %>');">
  <div class="container text-center">
    <h1><%= @cocktail.name %></h1>
  </div>
</div>

<div class="container">
  <ul>
    <% @cocktail.doses.each do |dose| %>
      <li>
        <%= dose.description %> : <%= dose.ingredient.name %>
        <%= link_to "Delete", delete_doses_path(dose), method: :delete  %>
      </li>
    <% end %>
  </ul>

  <%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description  %>
  <%= f.association :ingredient %>
  <%= f.submit 'Add Dose', class: 'btn btn-danger' %>
  <% end %>

  <%= link_to 'Home', root_path, class:'btn btn-danger'  %>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>

</html>